// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/automation.dart';
import 'api/content.dart';
import 'api/error.dart';
import 'api/files.dart';
import 'api/panel.dart';
import 'api/players.dart';
import 'api/server.dart';
import 'api/settings.dart';
import 'api/types.dart';

import 'dart:async';
import 'dart:convert';

import 'frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  RustStreamSink<String> dco_decode_StreamSink_String_Sse(dynamic raw);

  @protected
  RustStreamSink<ProgressEvent> dco_decode_StreamSink_progress_event_Sse(
    dynamic raw,
  );

  @protected
  RustStreamSink<ServerRuntime> dco_decode_StreamSink_server_runtime_Sse(
    dynamic raw,
  );

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AddonInfo dco_decode_addon_info(dynamic raw);

  @protected
  AddonKind dco_decode_addon_kind(dynamic raw);

  @protected
  AddonUpdate dco_decode_addon_update(dynamic raw);

  @protected
  AdvancedSettings dco_decode_advanced_settings(dynamic raw);

  @protected
  AppLogLevel dco_decode_app_log_level(dynamic raw);

  @protected
  AppPaths dco_decode_app_paths(dynamic raw);

  @protected
  AppearanceSettings dco_decode_appearance_settings(dynamic raw);

  @protected
  BackupInfo dco_decode_backup_info(dynamic raw);

  @protected
  BackupSettings dco_decode_backup_settings(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  ContentSourceKind dco_decode_box_autoadd_content_source_kind(dynamic raw);

  @protected
  CreateServerRequest dco_decode_box_autoadd_create_server_request(dynamic raw);

  @protected
  double dco_decode_box_autoadd_f_64(dynamic raw);

  @protected
  int dco_decode_box_autoadd_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw);

  @protected
  JavaVendor dco_decode_box_autoadd_java_vendor(dynamic raw);

  @protected
  LauncherSettings dco_decode_box_autoadd_launcher_settings(dynamic raw);

  @protected
  ModpackRequest dco_decode_box_autoadd_modpack_request(dynamic raw);

  @protected
  ServerConfig dco_decode_box_autoadd_server_config(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  UpdateInfo dco_decode_box_autoadd_update_info(dynamic raw);

  @protected
  BuildEntry dco_decode_build_entry(dynamic raw);

  @protected
  CloseBehavior dco_decode_close_behavior(dynamic raw);

  @protected
  ConsoleSettings dco_decode_console_settings(dynamic raw);

  @protected
  ContentPage dco_decode_content_page(dynamic raw);

  @protected
  ContentProject dco_decode_content_project(dynamic raw);

  @protected
  ContentSourceKind dco_decode_content_source_kind(dynamic raw);

  @protected
  ContentVersion dco_decode_content_version(dynamic raw);

  @protected
  CreateServerRequest dco_decode_create_server_request(dynamic raw);

  @protected
  DefaultsSettings dco_decode_defaults_settings(dynamic raw);

  @protected
  ErrorCode dco_decode_error_code(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  FileEntry dco_decode_file_entry(dynamic raw);

  @protected
  GeneralSettings dco_decode_general_settings(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  ImportPreview dco_decode_import_preview(dynamic raw);

  @protected
  IpBan dco_decode_ip_ban(dynamic raw);

  @protected
  JavaReleaseInfo dco_decode_java_release_info(dynamic raw);

  @protected
  JavaRuntimeInfo dco_decode_java_runtime_info(dynamic raw);

  @protected
  JavaSettings dco_decode_java_settings(dynamic raw);

  @protected
  JavaVendor dco_decode_java_vendor(dynamic raw);

  @protected
  JavaVendorInfo dco_decode_java_vendor_info(dynamic raw);

  @protected
  JvmPreset dco_decode_jvm_preset(dynamic raw);

  @protected
  JvmPresetInfo dco_decode_jvm_preset_info(dynamic raw);

  @protected
  LauncherSettings dco_decode_launcher_settings(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<AddonInfo> dco_decode_list_addon_info(dynamic raw);

  @protected
  List<AddonUpdate> dco_decode_list_addon_update(dynamic raw);

  @protected
  List<BackupInfo> dco_decode_list_backup_info(dynamic raw);

  @protected
  List<BuildEntry> dco_decode_list_build_entry(dynamic raw);

  @protected
  List<ContentProject> dco_decode_list_content_project(dynamic raw);

  @protected
  List<ContentSourceKind> dco_decode_list_content_source_kind(dynamic raw);

  @protected
  List<ContentVersion> dco_decode_list_content_version(dynamic raw);

  @protected
  List<FileEntry> dco_decode_list_file_entry(dynamic raw);

  @protected
  List<IpBan> dco_decode_list_ip_ban(dynamic raw);

  @protected
  List<JavaReleaseInfo> dco_decode_list_java_release_info(dynamic raw);

  @protected
  List<JavaRuntimeInfo> dco_decode_list_java_runtime_info(dynamic raw);

  @protected
  List<JavaVendorInfo> dco_decode_list_java_vendor_info(dynamic raw);

  @protected
  List<JvmPresetInfo> dco_decode_list_jvm_preset_info(dynamic raw);

  @protected
  List<LogFileInfo> dco_decode_list_log_file_info(dynamic raw);

  @protected
  List<PlayerEntry> dco_decode_list_player_entry(dynamic raw);

  @protected
  List<PreferredJava> dco_decode_list_preferred_java(dynamic raw);

  @protected
  Int64List dco_decode_list_prim_i_64_strict(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<PropertyEntry> dco_decode_list_property_entry(dynamic raw);

  @protected
  List<PropertySchema> dco_decode_list_property_schema(dynamic raw);

  @protected
  List<ProviderInfo> dco_decode_list_provider_info(dynamic raw);

  @protected
  List<RamChoice> dco_decode_list_ram_choice(dynamic raw);

  @protected
  List<ScheduledTask> dco_decode_list_scheduled_task(dynamic raw);

  @protected
  List<ServerRuntime> dco_decode_list_server_runtime(dynamic raw);

  @protected
  List<ServerSummary> dco_decode_list_server_summary(dynamic raw);

  @protected
  List<VersionEntry> dco_decode_list_version_entry(dynamic raw);

  @protected
  List<WorldInfo> dco_decode_list_world_info(dynamic raw);

  @protected
  LogFileInfo dco_decode_log_file_info(dynamic raw);

  @protected
  LogFileKind dco_decode_log_file_kind(dynamic raw);

  @protected
  ManagedFolder dco_decode_managed_folder(dynamic raw);

  @protected
  ModpackRequest dco_decode_modpack_request(dynamic raw);

  @protected
  NetworkSettings dco_decode_network_settings(dynamic raw);

  @protected
  NotificationSettings dco_decode_notification_settings(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  ContentSourceKind? dco_decode_opt_box_autoadd_content_source_kind(
    dynamic raw,
  );

  @protected
  double? dco_decode_opt_box_autoadd_f_64(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_i_32(dynamic raw);

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw);

  @protected
  JavaVendor? dco_decode_opt_box_autoadd_java_vendor(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  UpdateInfo? dco_decode_opt_box_autoadd_update_info(dynamic raw);

  @protected
  PanelError dco_decode_panel_error(dynamic raw);

  @protected
  PathSettings dco_decode_path_settings(dynamic raw);

  @protected
  PlayerEntry dco_decode_player_entry(dynamic raw);

  @protected
  PlayerListKind dco_decode_player_list_kind(dynamic raw);

  @protected
  PlayerLists dco_decode_player_lists(dynamic raw);

  @protected
  PreferredJava dco_decode_preferred_java(dynamic raw);

  @protected
  ProgressEvent dco_decode_progress_event(dynamic raw);

  @protected
  PropertyEntry dco_decode_property_entry(dynamic raw);

  @protected
  PropertyGroup dco_decode_property_group(dynamic raw);

  @protected
  PropertyKind dco_decode_property_kind(dynamic raw);

  @protected
  PropertySchema dco_decode_property_schema(dynamic raw);

  @protected
  ProviderCategory dco_decode_provider_category(dynamic raw);

  @protected
  ProviderInfo dco_decode_provider_info(dynamic raw);

  @protected
  ProviderKind dco_decode_provider_kind(dynamic raw);

  @protected
  RamChoice dco_decode_ram_choice(dynamic raw);

  @protected
  RamSuggestion dco_decode_ram_suggestion(dynamic raw);

  @protected
  ScheduleKind dco_decode_schedule_kind(dynamic raw);

  @protected
  ScheduledTask dco_decode_scheduled_task(dynamic raw);

  @protected
  ServerConfig dco_decode_server_config(dynamic raw);

  @protected
  ServerDetails dco_decode_server_details(dynamic raw);

  @protected
  ServerRuntime dco_decode_server_runtime(dynamic raw);

  @protected
  ServerStatus dco_decode_server_status(dynamic raw);

  @protected
  ServerSummary dco_decode_server_summary(dynamic raw);

  @protected
  ThemePreference dco_decode_theme_preference(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  UpdateInfo dco_decode_update_info(dynamic raw);

  @protected
  VersionEntry dco_decode_version_entry(dynamic raw);

  @protected
  WorldDimension dco_decode_world_dimension(dynamic raw);

  @protected
  WorldInfo dco_decode_world_info(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  RustStreamSink<String> sse_decode_StreamSink_String_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<ProgressEvent> sse_decode_StreamSink_progress_event_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<ServerRuntime> sse_decode_StreamSink_server_runtime_Sse(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AddonInfo sse_decode_addon_info(SseDeserializer deserializer);

  @protected
  AddonKind sse_decode_addon_kind(SseDeserializer deserializer);

  @protected
  AddonUpdate sse_decode_addon_update(SseDeserializer deserializer);

  @protected
  AdvancedSettings sse_decode_advanced_settings(SseDeserializer deserializer);

  @protected
  AppLogLevel sse_decode_app_log_level(SseDeserializer deserializer);

  @protected
  AppPaths sse_decode_app_paths(SseDeserializer deserializer);

  @protected
  AppearanceSettings sse_decode_appearance_settings(
    SseDeserializer deserializer,
  );

  @protected
  BackupInfo sse_decode_backup_info(SseDeserializer deserializer);

  @protected
  BackupSettings sse_decode_backup_settings(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  ContentSourceKind sse_decode_box_autoadd_content_source_kind(
    SseDeserializer deserializer,
  );

  @protected
  CreateServerRequest sse_decode_box_autoadd_create_server_request(
    SseDeserializer deserializer,
  );

  @protected
  double sse_decode_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  JavaVendor sse_decode_box_autoadd_java_vendor(SseDeserializer deserializer);

  @protected
  LauncherSettings sse_decode_box_autoadd_launcher_settings(
    SseDeserializer deserializer,
  );

  @protected
  ModpackRequest sse_decode_box_autoadd_modpack_request(
    SseDeserializer deserializer,
  );

  @protected
  ServerConfig sse_decode_box_autoadd_server_config(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  UpdateInfo sse_decode_box_autoadd_update_info(SseDeserializer deserializer);

  @protected
  BuildEntry sse_decode_build_entry(SseDeserializer deserializer);

  @protected
  CloseBehavior sse_decode_close_behavior(SseDeserializer deserializer);

  @protected
  ConsoleSettings sse_decode_console_settings(SseDeserializer deserializer);

  @protected
  ContentPage sse_decode_content_page(SseDeserializer deserializer);

  @protected
  ContentProject sse_decode_content_project(SseDeserializer deserializer);

  @protected
  ContentSourceKind sse_decode_content_source_kind(
    SseDeserializer deserializer,
  );

  @protected
  ContentVersion sse_decode_content_version(SseDeserializer deserializer);

  @protected
  CreateServerRequest sse_decode_create_server_request(
    SseDeserializer deserializer,
  );

  @protected
  DefaultsSettings sse_decode_defaults_settings(SseDeserializer deserializer);

  @protected
  ErrorCode sse_decode_error_code(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  FileEntry sse_decode_file_entry(SseDeserializer deserializer);

  @protected
  GeneralSettings sse_decode_general_settings(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  ImportPreview sse_decode_import_preview(SseDeserializer deserializer);

  @protected
  IpBan sse_decode_ip_ban(SseDeserializer deserializer);

  @protected
  JavaReleaseInfo sse_decode_java_release_info(SseDeserializer deserializer);

  @protected
  JavaRuntimeInfo sse_decode_java_runtime_info(SseDeserializer deserializer);

  @protected
  JavaSettings sse_decode_java_settings(SseDeserializer deserializer);

  @protected
  JavaVendor sse_decode_java_vendor(SseDeserializer deserializer);

  @protected
  JavaVendorInfo sse_decode_java_vendor_info(SseDeserializer deserializer);

  @protected
  JvmPreset sse_decode_jvm_preset(SseDeserializer deserializer);

  @protected
  JvmPresetInfo sse_decode_jvm_preset_info(SseDeserializer deserializer);

  @protected
  LauncherSettings sse_decode_launcher_settings(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<AddonInfo> sse_decode_list_addon_info(SseDeserializer deserializer);

  @protected
  List<AddonUpdate> sse_decode_list_addon_update(SseDeserializer deserializer);

  @protected
  List<BackupInfo> sse_decode_list_backup_info(SseDeserializer deserializer);

  @protected
  List<BuildEntry> sse_decode_list_build_entry(SseDeserializer deserializer);

  @protected
  List<ContentProject> sse_decode_list_content_project(
    SseDeserializer deserializer,
  );

  @protected
  List<ContentSourceKind> sse_decode_list_content_source_kind(
    SseDeserializer deserializer,
  );

  @protected
  List<ContentVersion> sse_decode_list_content_version(
    SseDeserializer deserializer,
  );

  @protected
  List<FileEntry> sse_decode_list_file_entry(SseDeserializer deserializer);

  @protected
  List<IpBan> sse_decode_list_ip_ban(SseDeserializer deserializer);

  @protected
  List<JavaReleaseInfo> sse_decode_list_java_release_info(
    SseDeserializer deserializer,
  );

  @protected
  List<JavaRuntimeInfo> sse_decode_list_java_runtime_info(
    SseDeserializer deserializer,
  );

  @protected
  List<JavaVendorInfo> sse_decode_list_java_vendor_info(
    SseDeserializer deserializer,
  );

  @protected
  List<JvmPresetInfo> sse_decode_list_jvm_preset_info(
    SseDeserializer deserializer,
  );

  @protected
  List<LogFileInfo> sse_decode_list_log_file_info(SseDeserializer deserializer);

  @protected
  List<PlayerEntry> sse_decode_list_player_entry(SseDeserializer deserializer);

  @protected
  List<PreferredJava> sse_decode_list_preferred_java(
    SseDeserializer deserializer,
  );

  @protected
  Int64List sse_decode_list_prim_i_64_strict(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<PropertyEntry> sse_decode_list_property_entry(
    SseDeserializer deserializer,
  );

  @protected
  List<PropertySchema> sse_decode_list_property_schema(
    SseDeserializer deserializer,
  );

  @protected
  List<ProviderInfo> sse_decode_list_provider_info(
    SseDeserializer deserializer,
  );

  @protected
  List<RamChoice> sse_decode_list_ram_choice(SseDeserializer deserializer);

  @protected
  List<ScheduledTask> sse_decode_list_scheduled_task(
    SseDeserializer deserializer,
  );

  @protected
  List<ServerRuntime> sse_decode_list_server_runtime(
    SseDeserializer deserializer,
  );

  @protected
  List<ServerSummary> sse_decode_list_server_summary(
    SseDeserializer deserializer,
  );

  @protected
  List<VersionEntry> sse_decode_list_version_entry(
    SseDeserializer deserializer,
  );

  @protected
  List<WorldInfo> sse_decode_list_world_info(SseDeserializer deserializer);

  @protected
  LogFileInfo sse_decode_log_file_info(SseDeserializer deserializer);

  @protected
  LogFileKind sse_decode_log_file_kind(SseDeserializer deserializer);

  @protected
  ManagedFolder sse_decode_managed_folder(SseDeserializer deserializer);

  @protected
  ModpackRequest sse_decode_modpack_request(SseDeserializer deserializer);

  @protected
  NetworkSettings sse_decode_network_settings(SseDeserializer deserializer);

  @protected
  NotificationSettings sse_decode_notification_settings(
    SseDeserializer deserializer,
  );

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  ContentSourceKind? sse_decode_opt_box_autoadd_content_source_kind(
    SseDeserializer deserializer,
  );

  @protected
  double? sse_decode_opt_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  JavaVendor? sse_decode_opt_box_autoadd_java_vendor(
    SseDeserializer deserializer,
  );

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  UpdateInfo? sse_decode_opt_box_autoadd_update_info(
    SseDeserializer deserializer,
  );

  @protected
  PanelError sse_decode_panel_error(SseDeserializer deserializer);

  @protected
  PathSettings sse_decode_path_settings(SseDeserializer deserializer);

  @protected
  PlayerEntry sse_decode_player_entry(SseDeserializer deserializer);

  @protected
  PlayerListKind sse_decode_player_list_kind(SseDeserializer deserializer);

  @protected
  PlayerLists sse_decode_player_lists(SseDeserializer deserializer);

  @protected
  PreferredJava sse_decode_preferred_java(SseDeserializer deserializer);

  @protected
  ProgressEvent sse_decode_progress_event(SseDeserializer deserializer);

  @protected
  PropertyEntry sse_decode_property_entry(SseDeserializer deserializer);

  @protected
  PropertyGroup sse_decode_property_group(SseDeserializer deserializer);

  @protected
  PropertyKind sse_decode_property_kind(SseDeserializer deserializer);

  @protected
  PropertySchema sse_decode_property_schema(SseDeserializer deserializer);

  @protected
  ProviderCategory sse_decode_provider_category(SseDeserializer deserializer);

  @protected
  ProviderInfo sse_decode_provider_info(SseDeserializer deserializer);

  @protected
  ProviderKind sse_decode_provider_kind(SseDeserializer deserializer);

  @protected
  RamChoice sse_decode_ram_choice(SseDeserializer deserializer);

  @protected
  RamSuggestion sse_decode_ram_suggestion(SseDeserializer deserializer);

  @protected
  ScheduleKind sse_decode_schedule_kind(SseDeserializer deserializer);

  @protected
  ScheduledTask sse_decode_scheduled_task(SseDeserializer deserializer);

  @protected
  ServerConfig sse_decode_server_config(SseDeserializer deserializer);

  @protected
  ServerDetails sse_decode_server_details(SseDeserializer deserializer);

  @protected
  ServerRuntime sse_decode_server_runtime(SseDeserializer deserializer);

  @protected
  ServerStatus sse_decode_server_status(SseDeserializer deserializer);

  @protected
  ServerSummary sse_decode_server_summary(SseDeserializer deserializer);

  @protected
  ThemePreference sse_decode_theme_preference(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  UpdateInfo sse_decode_update_info(SseDeserializer deserializer);

  @protected
  VersionEntry sse_decode_version_entry(SseDeserializer deserializer);

  @protected
  WorldDimension sse_decode_world_dimension(SseDeserializer deserializer);

  @protected
  WorldInfo sse_decode_world_info(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_String_Sse(
    RustStreamSink<String> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_progress_event_Sse(
    RustStreamSink<ProgressEvent> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_server_runtime_Sse(
    RustStreamSink<ServerRuntime> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_addon_info(AddonInfo self, SseSerializer serializer);

  @protected
  void sse_encode_addon_kind(AddonKind self, SseSerializer serializer);

  @protected
  void sse_encode_addon_update(AddonUpdate self, SseSerializer serializer);

  @protected
  void sse_encode_advanced_settings(
    AdvancedSettings self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_app_log_level(AppLogLevel self, SseSerializer serializer);

  @protected
  void sse_encode_app_paths(AppPaths self, SseSerializer serializer);

  @protected
  void sse_encode_appearance_settings(
    AppearanceSettings self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_backup_info(BackupInfo self, SseSerializer serializer);

  @protected
  void sse_encode_backup_settings(
    BackupSettings self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_content_source_kind(
    ContentSourceKind self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_create_server_request(
    CreateServerRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_java_vendor(
    JavaVendor self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_launcher_settings(
    LauncherSettings self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_modpack_request(
    ModpackRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_server_config(
    ServerConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_update_info(
    UpdateInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_build_entry(BuildEntry self, SseSerializer serializer);

  @protected
  void sse_encode_close_behavior(CloseBehavior self, SseSerializer serializer);

  @protected
  void sse_encode_console_settings(
    ConsoleSettings self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_content_page(ContentPage self, SseSerializer serializer);

  @protected
  void sse_encode_content_project(
    ContentProject self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_content_source_kind(
    ContentSourceKind self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_content_version(
    ContentVersion self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_create_server_request(
    CreateServerRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_defaults_settings(
    DefaultsSettings self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_error_code(ErrorCode self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_file_entry(FileEntry self, SseSerializer serializer);

  @protected
  void sse_encode_general_settings(
    GeneralSettings self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_import_preview(ImportPreview self, SseSerializer serializer);

  @protected
  void sse_encode_ip_ban(IpBan self, SseSerializer serializer);

  @protected
  void sse_encode_java_release_info(
    JavaReleaseInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_java_runtime_info(
    JavaRuntimeInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_java_settings(JavaSettings self, SseSerializer serializer);

  @protected
  void sse_encode_java_vendor(JavaVendor self, SseSerializer serializer);

  @protected
  void sse_encode_java_vendor_info(
    JavaVendorInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_jvm_preset(JvmPreset self, SseSerializer serializer);

  @protected
  void sse_encode_jvm_preset_info(JvmPresetInfo self, SseSerializer serializer);

  @protected
  void sse_encode_launcher_settings(
    LauncherSettings self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_addon_info(
    List<AddonInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_addon_update(
    List<AddonUpdate> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_backup_info(
    List<BackupInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_build_entry(
    List<BuildEntry> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_content_project(
    List<ContentProject> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_content_source_kind(
    List<ContentSourceKind> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_content_version(
    List<ContentVersion> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_file_entry(
    List<FileEntry> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_ip_ban(List<IpBan> self, SseSerializer serializer);

  @protected
  void sse_encode_list_java_release_info(
    List<JavaReleaseInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_java_runtime_info(
    List<JavaRuntimeInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_java_vendor_info(
    List<JavaVendorInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_jvm_preset_info(
    List<JvmPresetInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_log_file_info(
    List<LogFileInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_player_entry(
    List<PlayerEntry> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_preferred_java(
    List<PreferredJava> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_i_64_strict(
    Int64List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_property_entry(
    List<PropertyEntry> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_property_schema(
    List<PropertySchema> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_provider_info(
    List<ProviderInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_ram_choice(
    List<RamChoice> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_scheduled_task(
    List<ScheduledTask> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_server_runtime(
    List<ServerRuntime> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_server_summary(
    List<ServerSummary> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_version_entry(
    List<VersionEntry> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_world_info(
    List<WorldInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_log_file_info(LogFileInfo self, SseSerializer serializer);

  @protected
  void sse_encode_log_file_kind(LogFileKind self, SseSerializer serializer);

  @protected
  void sse_encode_managed_folder(ManagedFolder self, SseSerializer serializer);

  @protected
  void sse_encode_modpack_request(
    ModpackRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_network_settings(
    NetworkSettings self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_notification_settings(
    NotificationSettings self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_content_source_kind(
    ContentSourceKind? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_f_64(double? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_i_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_java_vendor(
    JavaVendor? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_update_info(
    UpdateInfo? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_panel_error(PanelError self, SseSerializer serializer);

  @protected
  void sse_encode_path_settings(PathSettings self, SseSerializer serializer);

  @protected
  void sse_encode_player_entry(PlayerEntry self, SseSerializer serializer);

  @protected
  void sse_encode_player_list_kind(
    PlayerListKind self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_player_lists(PlayerLists self, SseSerializer serializer);

  @protected
  void sse_encode_preferred_java(PreferredJava self, SseSerializer serializer);

  @protected
  void sse_encode_progress_event(ProgressEvent self, SseSerializer serializer);

  @protected
  void sse_encode_property_entry(PropertyEntry self, SseSerializer serializer);

  @protected
  void sse_encode_property_group(PropertyGroup self, SseSerializer serializer);

  @protected
  void sse_encode_property_kind(PropertyKind self, SseSerializer serializer);

  @protected
  void sse_encode_property_schema(
    PropertySchema self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_provider_category(
    ProviderCategory self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_provider_info(ProviderInfo self, SseSerializer serializer);

  @protected
  void sse_encode_provider_kind(ProviderKind self, SseSerializer serializer);

  @protected
  void sse_encode_ram_choice(RamChoice self, SseSerializer serializer);

  @protected
  void sse_encode_ram_suggestion(RamSuggestion self, SseSerializer serializer);

  @protected
  void sse_encode_schedule_kind(ScheduleKind self, SseSerializer serializer);

  @protected
  void sse_encode_scheduled_task(ScheduledTask self, SseSerializer serializer);

  @protected
  void sse_encode_server_config(ServerConfig self, SseSerializer serializer);

  @protected
  void sse_encode_server_details(ServerDetails self, SseSerializer serializer);

  @protected
  void sse_encode_server_runtime(ServerRuntime self, SseSerializer serializer);

  @protected
  void sse_encode_server_status(ServerStatus self, SseSerializer serializer);

  @protected
  void sse_encode_server_summary(ServerSummary self, SseSerializer serializer);

  @protected
  void sse_encode_theme_preference(
    ThemePreference self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_update_info(UpdateInfo self, SseSerializer serializer);

  @protected
  void sse_encode_version_entry(VersionEntry self, SseSerializer serializer);

  @protected
  void sse_encode_world_dimension(
    WorldDimension self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_world_info(WorldInfo self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
