// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/error.dart';
import 'api/files.dart';
import 'api/panel.dart';
import 'api/types.dart';

import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;

import 'frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  RustStreamSink<String> dco_decode_StreamSink_String_Sse(dynamic raw);

  @protected
  RustStreamSink<ProgressEvent> dco_decode_StreamSink_progress_event_Sse(
    dynamic raw,
  );

  @protected
  RustStreamSink<ServerRuntime> dco_decode_StreamSink_server_runtime_Sse(
    dynamic raw,
  );

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AppPaths dco_decode_app_paths(dynamic raw);

  @protected
  AutoInstallRequest dco_decode_auto_install_request(dynamic raw);

  @protected
  BackupInfo dco_decode_backup_info(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  AutoInstallRequest dco_decode_box_autoadd_auto_install_request(dynamic raw);

  @protected
  double dco_decode_box_autoadd_f_64(dynamic raw);

  @protected
  int dco_decode_box_autoadd_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw);

  @protected
  ManualInstallRequest dco_decode_box_autoadd_manual_install_request(
    dynamic raw,
  );

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  ErrorCode dco_decode_error_code(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  ImportPreview dco_decode_import_preview(dynamic raw);

  @protected
  JavaReleaseInfo dco_decode_java_release_info(dynamic raw);

  @protected
  JavaRuntimeInfo dco_decode_java_runtime_info(dynamic raw);

  @protected
  JvmFlagChoice dco_decode_jvm_flag_choice(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<BackupInfo> dco_decode_list_backup_info(dynamic raw);

  @protected
  List<JavaReleaseInfo> dco_decode_list_java_release_info(dynamic raw);

  @protected
  List<JavaRuntimeInfo> dco_decode_list_java_runtime_info(dynamic raw);

  @protected
  List<JvmFlagChoice> dco_decode_list_jvm_flag_choice(dynamic raw);

  @protected
  List<ModrinthProject> dco_decode_list_modrinth_project(dynamic raw);

  @protected
  List<PluginInfo> dco_decode_list_plugin_info(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<PropertyEntry> dco_decode_list_property_entry(dynamic raw);

  @protected
  List<RamChoice> dco_decode_list_ram_choice(dynamic raw);

  @protected
  List<ServerRuntime> dco_decode_list_server_runtime(dynamic raw);

  @protected
  List<ServerSummary> dco_decode_list_server_summary(dynamic raw);

  @protected
  List<WorldInfo> dco_decode_list_world_info(dynamic raw);

  @protected
  ManualInstallRequest dco_decode_manual_install_request(dynamic raw);

  @protected
  ModrinthProject dco_decode_modrinth_project(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  double? dco_decode_opt_box_autoadd_f_64(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_i_32(dynamic raw);

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  PanelError dco_decode_panel_error(dynamic raw);

  @protected
  PluginInfo dco_decode_plugin_info(dynamic raw);

  @protected
  ProgressEvent dco_decode_progress_event(dynamic raw);

  @protected
  PropertyEntry dco_decode_property_entry(dynamic raw);

  @protected
  RamChoice dco_decode_ram_choice(dynamic raw);

  @protected
  RamSuggestion dco_decode_ram_suggestion(dynamic raw);

  @protected
  ServerDetails dco_decode_server_details(dynamic raw);

  @protected
  ServerRuntime dco_decode_server_runtime(dynamic raw);

  @protected
  ServerStatus dco_decode_server_status(dynamic raw);

  @protected
  ServerSummary dco_decode_server_summary(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  WorldInfo dco_decode_world_info(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  RustStreamSink<String> sse_decode_StreamSink_String_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<ProgressEvent> sse_decode_StreamSink_progress_event_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<ServerRuntime> sse_decode_StreamSink_server_runtime_Sse(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AppPaths sse_decode_app_paths(SseDeserializer deserializer);

  @protected
  AutoInstallRequest sse_decode_auto_install_request(
    SseDeserializer deserializer,
  );

  @protected
  BackupInfo sse_decode_backup_info(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  AutoInstallRequest sse_decode_box_autoadd_auto_install_request(
    SseDeserializer deserializer,
  );

  @protected
  double sse_decode_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  ManualInstallRequest sse_decode_box_autoadd_manual_install_request(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  ErrorCode sse_decode_error_code(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  ImportPreview sse_decode_import_preview(SseDeserializer deserializer);

  @protected
  JavaReleaseInfo sse_decode_java_release_info(SseDeserializer deserializer);

  @protected
  JavaRuntimeInfo sse_decode_java_runtime_info(SseDeserializer deserializer);

  @protected
  JvmFlagChoice sse_decode_jvm_flag_choice(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<BackupInfo> sse_decode_list_backup_info(SseDeserializer deserializer);

  @protected
  List<JavaReleaseInfo> sse_decode_list_java_release_info(
    SseDeserializer deserializer,
  );

  @protected
  List<JavaRuntimeInfo> sse_decode_list_java_runtime_info(
    SseDeserializer deserializer,
  );

  @protected
  List<JvmFlagChoice> sse_decode_list_jvm_flag_choice(
    SseDeserializer deserializer,
  );

  @protected
  List<ModrinthProject> sse_decode_list_modrinth_project(
    SseDeserializer deserializer,
  );

  @protected
  List<PluginInfo> sse_decode_list_plugin_info(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<PropertyEntry> sse_decode_list_property_entry(
    SseDeserializer deserializer,
  );

  @protected
  List<RamChoice> sse_decode_list_ram_choice(SseDeserializer deserializer);

  @protected
  List<ServerRuntime> sse_decode_list_server_runtime(
    SseDeserializer deserializer,
  );

  @protected
  List<ServerSummary> sse_decode_list_server_summary(
    SseDeserializer deserializer,
  );

  @protected
  List<WorldInfo> sse_decode_list_world_info(SseDeserializer deserializer);

  @protected
  ManualInstallRequest sse_decode_manual_install_request(
    SseDeserializer deserializer,
  );

  @protected
  ModrinthProject sse_decode_modrinth_project(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  double? sse_decode_opt_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  PanelError sse_decode_panel_error(SseDeserializer deserializer);

  @protected
  PluginInfo sse_decode_plugin_info(SseDeserializer deserializer);

  @protected
  ProgressEvent sse_decode_progress_event(SseDeserializer deserializer);

  @protected
  PropertyEntry sse_decode_property_entry(SseDeserializer deserializer);

  @protected
  RamChoice sse_decode_ram_choice(SseDeserializer deserializer);

  @protected
  RamSuggestion sse_decode_ram_suggestion(SseDeserializer deserializer);

  @protected
  ServerDetails sse_decode_server_details(SseDeserializer deserializer);

  @protected
  ServerRuntime sse_decode_server_runtime(SseDeserializer deserializer);

  @protected
  ServerStatus sse_decode_server_status(SseDeserializer deserializer);

  @protected
  ServerSummary sse_decode_server_summary(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  WorldInfo sse_decode_world_info(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_String_Sse(
    RustStreamSink<String> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_progress_event_Sse(
    RustStreamSink<ProgressEvent> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_server_runtime_Sse(
    RustStreamSink<ServerRuntime> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_app_paths(AppPaths self, SseSerializer serializer);

  @protected
  void sse_encode_auto_install_request(
    AutoInstallRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_backup_info(BackupInfo self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_auto_install_request(
    AutoInstallRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_manual_install_request(
    ManualInstallRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_error_code(ErrorCode self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_import_preview(ImportPreview self, SseSerializer serializer);

  @protected
  void sse_encode_java_release_info(
    JavaReleaseInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_java_runtime_info(
    JavaRuntimeInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_jvm_flag_choice(JvmFlagChoice self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_backup_info(
    List<BackupInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_java_release_info(
    List<JavaReleaseInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_java_runtime_info(
    List<JavaRuntimeInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_jvm_flag_choice(
    List<JvmFlagChoice> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_modrinth_project(
    List<ModrinthProject> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_plugin_info(
    List<PluginInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_property_entry(
    List<PropertyEntry> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_ram_choice(
    List<RamChoice> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_server_runtime(
    List<ServerRuntime> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_server_summary(
    List<ServerSummary> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_world_info(
    List<WorldInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_manual_install_request(
    ManualInstallRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_modrinth_project(
    ModrinthProject self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_f_64(double? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_i_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_panel_error(PanelError self, SseSerializer serializer);

  @protected
  void sse_encode_plugin_info(PluginInfo self, SseSerializer serializer);

  @protected
  void sse_encode_progress_event(ProgressEvent self, SseSerializer serializer);

  @protected
  void sse_encode_property_entry(PropertyEntry self, SseSerializer serializer);

  @protected
  void sse_encode_ram_choice(RamChoice self, SseSerializer serializer);

  @protected
  void sse_encode_ram_suggestion(RamSuggestion self, SseSerializer serializer);

  @protected
  void sse_encode_server_details(ServerDetails self, SseSerializer serializer);

  @protected
  void sse_encode_server_runtime(ServerRuntime self, SseSerializer serializer);

  @protected
  void sse_encode_server_status(ServerStatus self, SseSerializer serializer);

  @protected
  void sse_encode_server_summary(ServerSummary self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_world_info(WorldInfo self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;
}
