// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'error.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import 'types.dart';

Future<List<ScheduledTask>> listSchedules({required String id}) =>
    RustLib.instance.api.crateApiAutomationListSchedules(id: id);

/// Replaces the scheduled tasks of a server; every task is validated first.
Future<void> saveSchedules({
  required String id,
  required List<ScheduledTask> tasks,
}) =>
    RustLib.instance.api.crateApiAutomationSaveSchedules(id: id, tasks: tasks);

/// Next run times (unix seconds) of a cron expression, for previews while editing.
Int64List nextScheduleRuns({required String cron, required int count}) =>
    RustLib.instance.api.crateApiAutomationNextScheduleRuns(
      cron: cron,
      count: count,
    );

Future<void> runScheduleNow({required String id, required String taskId}) =>
    RustLib.instance.api.crateApiAutomationRunScheduleNow(
      id: id,
      taskId: taskId,
    );

/// Starts the servers marked for autostart (when enabled in the launcher settings); returns their names.
Future<List<String>> autostartServers() =>
    RustLib.instance.api.crateApiAutomationAutostartServers();

/// Size of the server folder in bytes.
Future<PlatformInt64> serverDiskUsage({required String id}) =>
    RustLib.instance.api.crateApiAutomationServerDiskUsage(id: id);
