// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'error.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import 'types.dart';

// These functions are ignored because they are not marked as `pub`: `target`

/// Catalogues that offer plugins or mods for this server.
Future<List<ContentSourceKind>> contentSources({
  required String id,
  required AddonKind kind,
}) => RustLib.instance.api.crateApiContentContentSources(id: id, kind: kind);

Future<ContentPage> searchContent({
  required String id,
  required AddonKind kind,
  required ContentSourceKind source,
  required String query,
  required int page,
}) => RustLib.instance.api.crateApiContentSearchContent(
  id: id,
  kind: kind,
  source: source,
  query: query,
  page: page,
);

Future<List<ContentVersion>> contentVersions({
  required String id,
  required AddonKind kind,
  required ContentSourceKind source,
  required String projectId,
}) => RustLib.instance.api.crateApiContentContentVersions(
  id: id,
  kind: kind,
  source: source,
  projectId: projectId,
);

/// Installs a plugin or mod with its required dependencies. `version_id` empty: newest compatible.
Stream<ProgressEvent> installContent({
  required String id,
  required AddonKind kind,
  required ContentSourceKind source,
  required String projectId,
  required String versionId,
}) => RustLib.instance.api.crateApiContentInstallContent(
  id: id,
  kind: kind,
  source: source,
  projectId: projectId,
  versionId: versionId,
);

Future<List<AddonUpdate>> checkAddonUpdates({
  required String id,
  required AddonKind kind,
}) => RustLib.instance.api.crateApiContentCheckAddonUpdates(id: id, kind: kind);

Stream<ProgressEvent> updateAddons({
  required String id,
  required AddonKind kind,
  required List<AddonUpdate> updates,
}) => RustLib.instance.api.crateApiContentUpdateAddons(
  id: id,
  kind: kind,
  updates: updates,
);

List<ContentSourceKind> modpackSources() =>
    RustLib.instance.api.crateApiContentModpackSources();

Future<ContentPage> searchModpacks({
  required ContentSourceKind source,
  required String query,
  required int page,
}) => RustLib.instance.api.crateApiContentSearchModpacks(
  source: source,
  query: query,
  page: page,
);

Future<List<ContentVersion>> modpackVersions({
  required ContentSourceKind source,
  required String projectId,
}) => RustLib.instance.api.crateApiContentModpackVersions(
  source: source,
  projectId: projectId,
);

/// Creates a server from a modpack: installs the right loader, downloads the server-side files
/// and copies the overrides.
Stream<ProgressEvent> createFromModpack({required ModpackRequest request}) =>
    RustLib.instance.api.crateApiContentCreateFromModpack(request: request);
