// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `clone`, `eq`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`, `from`, `from`, `from`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `invalid`, `io`, `network`, `new`, `not_found`, `running`, `stopped`

/// Stable error categories. The UI maps them to localized text and falls back to `message`.
enum ErrorCode {
  generic,
  notFound,
  invalidInput,
  serverRunning,
  serverStopped,
  eulaRequired,
  portInUse,
  network,
  io,
}

class PanelError implements FrbException {
  final ErrorCode code;
  final String message;

  const PanelError({required this.code, required this.message});

  @override
  int get hashCode => code.hashCode ^ message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PanelError &&
          runtimeType == other.runtimeType &&
          code == other.code &&
          message == other.message;
}
