// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'error.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import 'types.dart';

// These functions are ignored because they are not marked as `pub`: `backup_path`

Future<List<PropertyEntry>> listProperties({required String id}) =>
    RustLib.instance.api.crateApiFilesListProperties(id: id);

Future<void> saveProperties({
  required String id,
  required List<PropertyEntry> entries,
}) =>
    RustLib.instance.api.crateApiFilesSaveProperties(id: id, entries: entries);

Future<List<AddonInfo>> listAddons({
  required String id,
  required AddonKind kind,
}) => RustLib.instance.api.crateApiFilesListAddons(id: id, kind: kind);

Future<void> setAddonEnabled({
  required String id,
  required AddonKind kind,
  required String fileName,
  required bool enabled,
}) => RustLib.instance.api.crateApiFilesSetAddonEnabled(
  id: id,
  kind: kind,
  fileName: fileName,
  enabled: enabled,
);

Future<void> deleteAddon({
  required String id,
  required AddonKind kind,
  required String fileName,
}) => RustLib.instance.api.crateApiFilesDeleteAddon(
  id: id,
  kind: kind,
  fileName: fileName,
);

Future<void> installAddonFile({
  required String id,
  required AddonKind kind,
  required String sourcePath,
}) => RustLib.instance.api.crateApiFilesInstallAddonFile(
  id: id,
  kind: kind,
  sourcePath: sourcePath,
);

/// Searches Modrinth for plugins or mods compatible with this server's software and version.
Future<List<ModrinthProject>> searchModrinth({
  required String id,
  required AddonKind kind,
  required String query,
}) => RustLib.instance.api.crateApiFilesSearchModrinth(
  id: id,
  kind: kind,
  query: query,
);

Stream<ProgressEvent> installModrinthProject({
  required String id,
  required AddonKind kind,
  required String projectId,
}) => RustLib.instance.api.crateApiFilesInstallModrinthProject(
  id: id,
  kind: kind,
  projectId: projectId,
);

Future<List<WorldInfo>> listWorlds({required String id}) =>
    RustLib.instance.api.crateApiFilesListWorlds(id: id);

Future<void> setActiveWorld({required String id, required String name}) =>
    RustLib.instance.api.crateApiFilesSetActiveWorld(id: id, name: name);

Future<void> deleteWorld({required String id, required String name}) =>
    RustLib.instance.api.crateApiFilesDeleteWorld(id: id, name: name);

/// Imports a world from a folder or a `.zip` under the given name.
Future<void> importWorld({
  required String id,
  required String sourcePath,
  required String name,
}) => RustLib.instance.api.crateApiFilesImportWorld(
  id: id,
  sourcePath: sourcePath,
  name: name,
);

/// Renames a world with its dimensions, keeping it active if it was.
Future<void> renameWorld({
  required String id,
  required String name,
  required String newName,
}) => RustLib.instance.api.crateApiFilesRenameWorld(
  id: id,
  name: name,
  newName: newName,
);

/// Deletes a world and its dimensions so the next start generates a new one, optionally with a new seed.
Future<void> resetWorld({
  required String id,
  required String name,
  required String seed,
}) => RustLib.instance.api.crateApiFilesResetWorld(
  id: id,
  name: name,
  seed: seed,
);

Stream<ProgressEvent> backupWorld({required String id, required String name}) =>
    RustLib.instance.api.crateApiFilesBackupWorld(id: id, name: name);

Future<void> openInExplorer({required String path}) =>
    RustLib.instance.api.crateApiFilesOpenInExplorer(path: path);

Future<List<BackupInfo>> listBackups({required String id}) =>
    RustLib.instance.api.crateApiFilesListBackups(id: id);

Stream<ProgressEvent> createBackup({required String id}) =>
    RustLib.instance.api.crateApiFilesCreateBackup(id: id);

Stream<ProgressEvent> restoreBackup({
  required String id,
  required String fileName,
}) =>
    RustLib.instance.api.crateApiFilesRestoreBackup(id: id, fileName: fileName);

Future<void> deleteBackup({required String id, required String fileName}) =>
    RustLib.instance.api.crateApiFilesDeleteBackup(id: id, fileName: fileName);
