// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import 'types.dart';

// These functions are ignored because they are not marked as `pub`: `from_settings`, `to_settings`

Future<ServerSettings> getSettings({required String id}) =>
    RustLib.instance.api.crateApiFilesGetSettings(id: id);

Future<void> saveSettings({
  required String id,
  required ServerSettings settings,
}) =>
    RustLib.instance.api.crateApiFilesSaveSettings(id: id, settings: settings);

Future<List<PluginInfo>> listPlugins({required String id}) =>
    RustLib.instance.api.crateApiFilesListPlugins(id: id);

Future<void> setPluginEnabled({
  required String id,
  required String fileName,
  required bool enabled,
}) => RustLib.instance.api.crateApiFilesSetPluginEnabled(
  id: id,
  fileName: fileName,
  enabled: enabled,
);

Future<void> deletePlugin({required String id, required String fileName}) =>
    RustLib.instance.api.crateApiFilesDeletePlugin(id: id, fileName: fileName);

Future<void> installPluginFile({
  required String id,
  required String sourcePath,
}) => RustLib.instance.api.crateApiFilesInstallPluginFile(
  id: id,
  sourcePath: sourcePath,
);

Future<List<ModrinthProject>> searchModrinth({required String query}) =>
    RustLib.instance.api.crateApiFilesSearchModrinth(query: query);

Stream<ProgressEvent> installModrinthProject({
  required String id,
  required String projectId,
}) => RustLib.instance.api.crateApiFilesInstallModrinthProject(
  id: id,
  projectId: projectId,
);

Future<List<WorldInfo>> listWorlds({required String id}) =>
    RustLib.instance.api.crateApiFilesListWorlds(id: id);

Future<void> setActiveWorld({required String id, required String name}) =>
    RustLib.instance.api.crateApiFilesSetActiveWorld(id: id, name: name);

Future<void> deleteWorld({required String id, required String name}) =>
    RustLib.instance.api.crateApiFilesDeleteWorld(id: id, name: name);

Future<void> openInExplorer({required String path}) =>
    RustLib.instance.api.crateApiFilesOpenInExplorer(path: path);

Future<List<BackupInfo>> listBackups({required String id}) =>
    RustLib.instance.api.crateApiFilesListBackups(id: id);

Stream<ProgressEvent> createBackup({required String id}) =>
    RustLib.instance.api.crateApiFilesCreateBackup(id: id);

Stream<ProgressEvent> restoreBackup({
  required String id,
  required String fileName,
}) =>
    RustLib.instance.api.crateApiFilesRestoreBackup(id: id, fileName: fileName);

Future<void> deleteBackup({required String id, required String fileName}) =>
    RustLib.instance.api.crateApiFilesDeleteBackup(id: id, fileName: fileName);

Future<bool> serverIsRunning({required String id}) =>
    RustLib.instance.api.crateApiFilesServerIsRunning(id: id);
