// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'error.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import 'types.dart';

// These functions are ignored because they are not marked as `pub`: `created_message`, `empty_to_none`, `to_runtime`, `to_status`

Future<List<ServerSummary>> listServers() =>
    RustLib.instance.api.crateApiPanelListServers();

Future<ServerDetails> getServer({required String id}) =>
    RustLib.instance.api.crateApiPanelGetServer(id: id);

/// Current runtime state of every server that has been started in this session.
Future<List<ServerRuntime>> runtimeSnapshots() =>
    RustLib.instance.api.crateApiPanelRuntimeSnapshots();

/// Streams runtime changes: current snapshots first, then every status, player or stats update.
Stream<ServerRuntime> watchEvents() =>
    RustLib.instance.api.crateApiPanelWatchEvents();

bool anyServerRunning() => RustLib.instance.api.crateApiPanelAnyServerRunning();

AppPaths appPaths() => RustLib.instance.api.crateApiPanelAppPaths();

List<RamChoice> ramPresets() => RustLib.instance.api.crateApiPanelRamPresets();

RamSuggestion suggestRam() => RustLib.instance.api.crateApiPanelSuggestRam();

List<JvmFlagChoice> jvmFlagChoices() =>
    RustLib.instance.api.crateApiPanelJvmFlagChoices();

Future<List<JavaRuntimeInfo>> listRuntimes() =>
    RustLib.instance.api.crateApiPanelListRuntimes();

Future<List<JavaReleaseInfo>> listJavaReleases() =>
    RustLib.instance.api.crateApiPanelListJavaReleases();

Future<List<String>> listPaperVersions() =>
    RustLib.instance.api.crateApiPanelListPaperVersions();

Future<ImportPreview> previewImport({required String path}) =>
    RustLib.instance.api.crateApiPanelPreviewImport(path: path);

Future<String> importServer({
  required String path,
  required String name,
  required bool acceptEula,
}) => RustLib.instance.api.crateApiPanelImportServer(
  path: path,
  name: name,
  acceptEula: acceptEula,
);

Future<void> acceptServerEula({required String id}) =>
    RustLib.instance.api.crateApiPanelAcceptServerEula(id: id);

Future<void> updateRuntimeConfig({
  required String id,
  required String javaHome,
  required String ramMin,
  required String ramMax,
  required List<String> jvmFlags,
}) => RustLib.instance.api.crateApiPanelUpdateRuntimeConfig(
  id: id,
  javaHome: javaHome,
  ramMin: ramMin,
  ramMax: ramMax,
  jvmFlags: jvmFlags,
);

Future<void> renameServer({required String id, required String name}) =>
    RustLib.instance.api.crateApiPanelRenameServer(id: id, name: name);

Future<void> deleteServer({
  required String id,
  required bool deleteFiles,
  required bool deleteBackups,
}) => RustLib.instance.api.crateApiPanelDeleteServer(
  id: id,
  deleteFiles: deleteFiles,
  deleteBackups: deleteBackups,
);

Future<void> startServer({required String id}) =>
    RustLib.instance.api.crateApiPanelStartServer(id: id);

Future<void> stopServer({required String id}) =>
    RustLib.instance.api.crateApiPanelStopServer(id: id);

Future<void> restartServer({required String id}) =>
    RustLib.instance.api.crateApiPanelRestartServer(id: id);

Future<void> sendCommand({required String id, required String command}) =>
    RustLib.instance.api.crateApiPanelSendCommand(id: id, command: command);

Future<void> shutdownAll() => RustLib.instance.api.crateApiPanelShutdownAll();

Stream<ProgressEvent> installAuto({required AutoInstallRequest request}) =>
    RustLib.instance.api.crateApiPanelInstallAuto(request: request);

Stream<ProgressEvent> installManual({required ManualInstallRequest request}) =>
    RustLib.instance.api.crateApiPanelInstallManual(request: request);

Stream<ProgressEvent> installJava({required int major}) =>
    RustLib.instance.api.crateApiPanelInstallJava(major: major);

Stream<String> watchConsole({required String id}) =>
    RustLib.instance.api.crateApiPanelWatchConsole(id: id);
