// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'error.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import 'settings.dart';
import 'types.dart';

// These functions are ignored because they are not marked as `pub`: `created_message`, `to_runtime`, `to_status`

Future<List<ServerSummary>> listServers() =>
    RustLib.instance.api.crateApiPanelListServers();

Future<ServerDetails> getServer({required String id}) =>
    RustLib.instance.api.crateApiPanelGetServer(id: id);

/// Current runtime state of every server that has been started in this session.
Future<List<ServerRuntime>> runtimeSnapshots() =>
    RustLib.instance.api.crateApiPanelRuntimeSnapshots();

/// Streams runtime changes: current snapshots first, then every status, player or stats update.
Stream<ServerRuntime> watchEvents() =>
    RustLib.instance.api.crateApiPanelWatchEvents();

bool anyServerRunning() => RustLib.instance.api.crateApiPanelAnyServerRunning();

AppPaths appPaths() => RustLib.instance.api.crateApiPanelAppPaths();

List<RamChoice> ramPresets() => RustLib.instance.api.crateApiPanelRamPresets();

/// Physical memory in MiB, used to cap the RAM a server can get.
BigInt systemMemoryMb() => RustLib.instance.api.crateApiPanelSystemMemoryMb();

RamSuggestion suggestRam() => RustLib.instance.api.crateApiPanelSuggestRam();

Future<List<JavaRuntimeInfo>> listRuntimes() =>
    RustLib.instance.api.crateApiPanelListRuntimes();

Future<List<JavaReleaseInfo>> listJavaReleases({required JavaVendor vendor}) =>
    RustLib.instance.api.crateApiPanelListJavaReleases(vendor: vendor);

/// Providers that VoxelPanel can install, in wizard order.
List<ProviderInfo> listProviders() =>
    RustLib.instance.api.crateApiPanelListProviders();

/// Metadata of any provider, also those only detected on import.
ProviderInfo providerInfo({required ProviderKind kind}) =>
    RustLib.instance.api.crateApiPanelProviderInfo(kind: kind);

Future<List<VersionEntry>> listVersions({
  required ProviderKind provider,
  required bool includeSnapshots,
}) => RustLib.instance.api.crateApiPanelListVersions(
  provider: provider,
  includeSnapshots: includeSnapshots,
);

Future<List<BuildEntry>> listBuilds({
  required ProviderKind provider,
  required String version,
}) => RustLib.instance.api.crateApiPanelListBuilds(
  provider: provider,
  version: version,
);

Future<int> requiredJava({
  required ProviderKind provider,
  required String version,
}) => RustLib.instance.api.crateApiPanelRequiredJava(
  provider: provider,
  version: version,
);

Future<ImportPreview> previewImport({required String path}) =>
    RustLib.instance.api.crateApiPanelPreviewImport(path: path);

Future<String> importServer({
  required String path,
  required String name,
  required bool acceptEula,
}) => RustLib.instance.api.crateApiPanelImportServer(
  path: path,
  name: name,
  acceptEula: acceptEula,
);

Future<void> acceptServerEula({required String id}) =>
    RustLib.instance.api.crateApiPanelAcceptServerEula(id: id);

Future<void> updateRuntimeConfig({
  required String id,
  required String javaHome,
  required String ramMin,
  required String ramMax,
  required List<String> jvmFlags,
}) => RustLib.instance.api.crateApiPanelUpdateRuntimeConfig(
  id: id,
  javaHome: javaHome,
  ramMin: ramMin,
  ramMax: ramMax,
  jvmFlags: jvmFlags,
);

Future<void> renameServer({required String id, required String name}) =>
    RustLib.instance.api.crateApiPanelRenameServer(id: id, name: name);

Future<void> deleteServer({
  required String id,
  required bool deleteFiles,
  required bool deleteBackups,
}) => RustLib.instance.api.crateApiPanelDeleteServer(
  id: id,
  deleteFiles: deleteFiles,
  deleteBackups: deleteBackups,
);

Future<void> startServer({required String id}) =>
    RustLib.instance.api.crateApiPanelStartServer(id: id);

Future<void> stopServer({required String id}) =>
    RustLib.instance.api.crateApiPanelStopServer(id: id);

Future<void> restartServer({required String id}) =>
    RustLib.instance.api.crateApiPanelRestartServer(id: id);

Future<void> sendCommand({required String id, required String command}) =>
    RustLib.instance.api.crateApiPanelSendCommand(id: id, command: command);

Future<void> shutdownAll() => RustLib.instance.api.crateApiPanelShutdownAll();

Stream<ProgressEvent> createServer({required CreateServerRequest request}) =>
    RustLib.instance.api.crateApiPanelCreateServer(request: request);

/// Installs another version or build of the same software, after an automatic backup.
Stream<ProgressEvent> changeServerVersion({
  required String id,
  required String mcVersion,
  required String build,
}) => RustLib.instance.api.crateApiPanelChangeServerVersion(
  id: id,
  mcVersion: mcVersion,
  build: build,
);

Stream<ProgressEvent> installJava({
  required int major,
  required JavaVendor vendor,
}) =>
    RustLib.instance.api.crateApiPanelInstallJava(major: major, vendor: vendor);

Stream<String> watchConsole({required String id}) =>
    RustLib.instance.api.crateApiPanelWatchConsole(id: id);
