// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'error.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import 'types.dart';

Future<PlayerLists> playerLists({required String id}) =>
    RustLib.instance.api.crateApiPlayersPlayerLists(id: id);

/// Online players: asked through RCON when available, otherwise taken from the console log.
Future<List<String>> onlinePlayers({required String id}) =>
    RustLib.instance.api.crateApiPlayersOnlinePlayers(id: id);

/// Runs a console command, through RCON when possible so that its output can be returned.
Future<String> runServerCommand({
  required String id,
  required String command,
}) => RustLib.instance.api.crateApiPlayersRunServerCommand(
  id: id,
  command: command,
);

/// Adds or removes a player (or an IP) from a list. Running servers get the equivalent command.
Future<void> modifyPlayerList({
  required String id,
  required PlayerListKind list,
  required bool add,
  required String target,
  required String reason,
}) => RustLib.instance.api.crateApiPlayersModifyPlayerList(
  id: id,
  list: list,
  add: add,
  target: target,
  reason: reason,
);
