// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'error.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import 'types.dart';

// These functions are ignored because they are not marked as `pub`: `record`

Future<ServerConfig> getServerConfig({required String id}) =>
    RustLib.instance.api.crateApiServerGetServerConfig(id: id);

/// Saves the per-server options. Runtime changes (Java, RAM, flags) need a stopped server.
Future<void> saveServerConfig({
  required String id,
  required ServerConfig config,
}) =>
    RustLib.instance.api.crateApiServerSaveServerConfig(id: id, config: config);

/// Path of `server-icon.png`, empty when the server has none.
Future<String> serverIconPath({required String id}) =>
    RustLib.instance.api.crateApiServerServerIconPath(id: id);

/// Converts any common image to the 64×64 PNG Minecraft expects.
Future<void> setServerIcon({required String id, required String sourcePath}) =>
    RustLib.instance.api.crateApiServerSetServerIcon(
      id: id,
      sourcePath: sourcePath,
    );

Future<void> removeServerIcon({required String id}) =>
    RustLib.instance.api.crateApiServerRemoveServerIcon(id: id);

List<PropertySchema> propertiesSchema() =>
    RustLib.instance.api.crateApiServerPropertiesSchema();

Future<List<String>> listConfigFiles({required String id}) =>
    RustLib.instance.api.crateApiServerListConfigFiles(id: id);

Future<List<FileEntry>> listDirectory({
  required String id,
  required String relative,
}) => RustLib.instance.api.crateApiServerListDirectory(
  id: id,
  relative: relative,
);

Future<String> readTextFile({required String id, required String relative}) =>
    RustLib.instance.api.crateApiServerReadTextFile(id: id, relative: relative);

Future<void> writeTextFile({
  required String id,
  required String relative,
  required String content,
}) => RustLib.instance.api.crateApiServerWriteTextFile(
  id: id,
  relative: relative,
  content: content,
);

Future<void> deleteServerPath({required String id, required String relative}) =>
    RustLib.instance.api.crateApiServerDeleteServerPath(
      id: id,
      relative: relative,
    );

Future<void> createServerDirectory({
  required String id,
  required String relative,
}) => RustLib.instance.api.crateApiServerCreateServerDirectory(
  id: id,
  relative: relative,
);

Future<void> renameServerPath({
  required String id,
  required String from,
  required String to,
}) => RustLib.instance.api.crateApiServerRenameServerPath(
  id: id,
  from: from,
  to: to,
);

Future<int> importServerFiles({
  required String id,
  required String relativeDir,
  required List<String> sources,
}) => RustLib.instance.api.crateApiServerImportServerFiles(
  id: id,
  relativeDir: relativeDir,
  sources: sources,
);

Future<String> exportServerPath({
  required String id,
  required String relative,
  required String destinationDir,
}) => RustLib.instance.api.crateApiServerExportServerPath(
  id: id,
  relative: relative,
  destinationDir: destinationDir,
);

Future<List<LogFileInfo>> listLogs({required String id}) =>
    RustLib.instance.api.crateApiServerListLogs(id: id);

Future<String> readLog({required String id, required String relative}) =>
    RustLib.instance.api.crateApiServerReadLog(id: id, relative: relative);
