// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'error.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

Future<LauncherSettings> getLauncherSettings() =>
    RustLib.instance.api.crateApiSettingsGetLauncherSettings();

Future<LauncherSettings> saveLauncherSettings({
  required LauncherSettings settings,
}) => RustLib.instance.api.crateApiSettingsSaveLauncherSettings(
  settings: settings,
);

Future<LauncherSettings> resetLauncherSettings() =>
    RustLib.instance.api.crateApiSettingsResetLauncherSettings();

/// JSON of the current settings without the CurseForge API key.
Future<String> exportLauncherSettings() =>
    RustLib.instance.api.crateApiSettingsExportLauncherSettings();

Future<LauncherSettings> importLauncherSettings({required String path}) =>
    RustLib.instance.api.crateApiSettingsImportLauncherSettings(path: path);

/// Moves the content of a managed folder and points the settings at `destination`.
/// Servers that reference moved Java runtimes are updated too.
Future<LauncherSettings> moveManagedFolder({
  required ManagedFolder folder,
  required String destination,
}) => RustLib.instance.api.crateApiSettingsMoveManagedFolder(
  folder: folder,
  destination: destination,
);

Future<void> clearCache() => RustLib.instance.api.crateApiSettingsClearCache();

List<JvmPresetInfo> jvmPresets() =>
    RustLib.instance.api.crateApiSettingsJvmPresets();

List<JavaVendorInfo> javaVendors() =>
    RustLib.instance.api.crateApiSettingsJavaVendors();

String appLogDir() => RustLib.instance.api.crateApiSettingsAppLogDir();

Future<UpdateInfo?> checkForUpdate({required String currentVersion}) => RustLib
    .instance
    .api
    .crateApiSettingsCheckForUpdate(currentVersion: currentVersion);

Future<void> deleteJavaRuntime({required String path}) =>
    RustLib.instance.api.crateApiSettingsDeleteJavaRuntime(path: path);

class AdvancedSettings {
  final bool logging;
  final AppLogLevel logLevel;

  const AdvancedSettings({required this.logging, required this.logLevel});

  static Future<AdvancedSettings> default_() =>
      RustLib.instance.api.crateApiSettingsAdvancedSettingsDefault();

  @override
  int get hashCode => logging.hashCode ^ logLevel.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AdvancedSettings &&
          runtimeType == other.runtimeType &&
          logging == other.logging &&
          logLevel == other.logLevel;
}

enum AppLogLevel {
  error,
  warn,
  info,
  debug;

  static Future<AppLogLevel> default_() =>
      RustLib.instance.api.crateApiSettingsAppLogLevelDefault();
}

class AppearanceSettings {
  final ThemePreference theme;

  /// ARGB, as used by Flutter's `Color`.
  final int accentColor;
  final double textScale;
  final bool compact;

  const AppearanceSettings({
    required this.theme,
    required this.accentColor,
    required this.textScale,
    required this.compact,
  });

  static Future<AppearanceSettings> default_() =>
      RustLib.instance.api.crateApiSettingsAppearanceSettingsDefault();

  @override
  int get hashCode =>
      theme.hashCode ^
      accentColor.hashCode ^
      textScale.hashCode ^
      compact.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AppearanceSettings &&
          runtimeType == other.runtimeType &&
          theme == other.theme &&
          accentColor == other.accentColor &&
          textScale == other.textScale &&
          compact == other.compact;
}

class BackupSettings {
  /// Backups kept per server; 0 keeps all of them.
  final int retention;
  final int compressionLevel;

  /// Paths relative to the server folder, or `*.ext` patterns.
  final List<String> exclusions;

  const BackupSettings({
    required this.retention,
    required this.compressionLevel,
    required this.exclusions,
  });

  static Future<BackupSettings> default_() =>
      RustLib.instance.api.crateApiSettingsBackupSettingsDefault();

  @override
  int get hashCode =>
      retention.hashCode ^ compressionLevel.hashCode ^ exclusions.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BackupSettings &&
          runtimeType == other.runtimeType &&
          retention == other.retention &&
          compressionLevel == other.compressionLevel &&
          exclusions == other.exclusions;
}

enum CloseBehavior {
  ask,
  stopAndExit,
  minimizeToTray;

  static Future<CloseBehavior> default_() =>
      RustLib.instance.api.crateApiSettingsCloseBehaviorDefault();
}

class ConsoleSettings {
  final int maxLines;
  final bool timestamps;
  final double fontSize;
  final bool wrap;

  const ConsoleSettings({
    required this.maxLines,
    required this.timestamps,
    required this.fontSize,
    required this.wrap,
  });

  static Future<ConsoleSettings> default_() =>
      RustLib.instance.api.crateApiSettingsConsoleSettingsDefault();

  @override
  int get hashCode =>
      maxLines.hashCode ^
      timestamps.hashCode ^
      fontSize.hashCode ^
      wrap.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ConsoleSettings &&
          runtimeType == other.runtimeType &&
          maxLines == other.maxLines &&
          timestamps == other.timestamps &&
          fontSize == other.fontSize &&
          wrap == other.wrap;
}

class DefaultsSettings {
  /// Empty means "suggest from system memory".
  final String ramMin;
  final String ramMax;
  final JvmPreset jvmPreset;
  final int port;
  final String provider;

  const DefaultsSettings({
    required this.ramMin,
    required this.ramMax,
    required this.jvmPreset,
    required this.port,
    required this.provider,
  });

  static Future<DefaultsSettings> default_() =>
      RustLib.instance.api.crateApiSettingsDefaultsSettingsDefault();

  @override
  int get hashCode =>
      ramMin.hashCode ^
      ramMax.hashCode ^
      jvmPreset.hashCode ^
      port.hashCode ^
      provider.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DefaultsSettings &&
          runtimeType == other.runtimeType &&
          ramMin == other.ramMin &&
          ramMax == other.ramMax &&
          jvmPreset == other.jvmPreset &&
          port == other.port &&
          provider == other.provider;
}

class GeneralSettings {
  /// "system", "it" or "en".
  final String language;
  final bool checkUpdates;
  final bool launchAtStartup;
  final CloseBehavior closeBehavior;
  final bool autostartServers;
  final int stopTimeoutSecs;

  const GeneralSettings({
    required this.language,
    required this.checkUpdates,
    required this.launchAtStartup,
    required this.closeBehavior,
    required this.autostartServers,
    required this.stopTimeoutSecs,
  });

  static Future<GeneralSettings> default_() =>
      RustLib.instance.api.crateApiSettingsGeneralSettingsDefault();

  @override
  int get hashCode =>
      language.hashCode ^
      checkUpdates.hashCode ^
      launchAtStartup.hashCode ^
      closeBehavior.hashCode ^
      autostartServers.hashCode ^
      stopTimeoutSecs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GeneralSettings &&
          runtimeType == other.runtimeType &&
          language == other.language &&
          checkUpdates == other.checkUpdates &&
          launchAtStartup == other.launchAtStartup &&
          closeBehavior == other.closeBehavior &&
          autostartServers == other.autostartServers &&
          stopTimeoutSecs == other.stopTimeoutSecs;
}

class JavaSettings {
  final List<PreferredJava> preferred;
  final JavaVendor vendor;

  const JavaSettings({required this.preferred, required this.vendor});

  static Future<JavaSettings> default_() =>
      RustLib.instance.api.crateApiSettingsJavaSettingsDefault();

  @override
  int get hashCode => preferred.hashCode ^ vendor.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is JavaSettings &&
          runtimeType == other.runtimeType &&
          preferred == other.preferred &&
          vendor == other.vendor;
}

/// Distribution used when VoxelPanel downloads a Java runtime.
enum JavaVendor {
  temurin,
  zulu,
  corretto,
  microsoft,
  liberica,
  sapMachine,
  graalVm;

  static Future<JavaVendor> default_() =>
      RustLib.instance.api.crateApiSettingsJavaVendorDefault();
}

class JavaVendorInfo {
  final JavaVendor vendor;
  final String name;
  final String publisher;
  final String website;

  const JavaVendorInfo({
    required this.vendor,
    required this.name,
    required this.publisher,
    required this.website,
  });

  @override
  int get hashCode =>
      vendor.hashCode ^ name.hashCode ^ publisher.hashCode ^ website.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is JavaVendorInfo &&
          runtimeType == other.runtimeType &&
          vendor == other.vendor &&
          name == other.name &&
          publisher == other.publisher &&
          website == other.website;
}

enum JvmPreset {
  aikar,
  g1,
  zgc,
  none;

  static Future<JvmPreset> default_() =>
      RustLib.instance.api.crateApiSettingsJvmPresetDefault();
}

class JvmPresetInfo {
  final JvmPreset preset;
  final List<String> flags;

  const JvmPresetInfo({required this.preset, required this.flags});

  @override
  int get hashCode => preset.hashCode ^ flags.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is JvmPresetInfo &&
          runtimeType == other.runtimeType &&
          preset == other.preset &&
          flags == other.flags;
}

class LauncherSettings {
  final int schemaVersion;
  final GeneralSettings general;
  final AppearanceSettings appearance;
  final PathSettings paths;
  final JavaSettings java;
  final DefaultsSettings defaults;
  final ConsoleSettings console;
  final BackupSettings backup;
  final NetworkSettings network;
  final NotificationSettings notifications;
  final AdvancedSettings advanced;

  const LauncherSettings({
    required this.schemaVersion,
    required this.general,
    required this.appearance,
    required this.paths,
    required this.java,
    required this.defaults,
    required this.console,
    required this.backup,
    required this.network,
    required this.notifications,
    required this.advanced,
  });

  static Future<LauncherSettings> default_() =>
      RustLib.instance.api.crateApiSettingsLauncherSettingsDefault();

  @override
  int get hashCode =>
      schemaVersion.hashCode ^
      general.hashCode ^
      appearance.hashCode ^
      paths.hashCode ^
      java.hashCode ^
      defaults.hashCode ^
      console.hashCode ^
      backup.hashCode ^
      network.hashCode ^
      notifications.hashCode ^
      advanced.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LauncherSettings &&
          runtimeType == other.runtimeType &&
          schemaVersion == other.schemaVersion &&
          general == other.general &&
          appearance == other.appearance &&
          paths == other.paths &&
          java == other.java &&
          defaults == other.defaults &&
          console == other.console &&
          backup == other.backup &&
          network == other.network &&
          notifications == other.notifications &&
          advanced == other.advanced;
}

enum ManagedFolder { servers, backups, runtimes, cache }

class NetworkSettings {
  final String proxy;
  final int parallelDownloads;
  final int timeoutSecs;
  final String curseforgeApiKey;

  const NetworkSettings({
    required this.proxy,
    required this.parallelDownloads,
    required this.timeoutSecs,
    required this.curseforgeApiKey,
  });

  static Future<NetworkSettings> default_() =>
      RustLib.instance.api.crateApiSettingsNetworkSettingsDefault();

  @override
  int get hashCode =>
      proxy.hashCode ^
      parallelDownloads.hashCode ^
      timeoutSecs.hashCode ^
      curseforgeApiKey.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NetworkSettings &&
          runtimeType == other.runtimeType &&
          proxy == other.proxy &&
          parallelDownloads == other.parallelDownloads &&
          timeoutSecs == other.timeoutSecs &&
          curseforgeApiKey == other.curseforgeApiKey;
}

class NotificationSettings {
  final bool crash;
  final bool ready;
  final bool playerJoin;

  const NotificationSettings({
    required this.crash,
    required this.ready,
    required this.playerJoin,
  });

  static Future<NotificationSettings> default_() =>
      RustLib.instance.api.crateApiSettingsNotificationSettingsDefault();

  @override
  int get hashCode => crash.hashCode ^ ready.hashCode ^ playerJoin.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NotificationSettings &&
          runtimeType == other.runtimeType &&
          crash == other.crash &&
          ready == other.ready &&
          playerJoin == other.playerJoin;
}

/// Empty strings mean "use the default folder inside the data directory".
class PathSettings {
  final String serversDir;
  final String backupsDir;
  final String runtimesDir;
  final String cacheDir;

  const PathSettings({
    required this.serversDir,
    required this.backupsDir,
    required this.runtimesDir,
    required this.cacheDir,
  });

  static Future<PathSettings> default_() =>
      RustLib.instance.api.crateApiSettingsPathSettingsDefault();

  @override
  int get hashCode =>
      serversDir.hashCode ^
      backupsDir.hashCode ^
      runtimesDir.hashCode ^
      cacheDir.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PathSettings &&
          runtimeType == other.runtimeType &&
          serversDir == other.serversDir &&
          backupsDir == other.backupsDir &&
          runtimesDir == other.runtimesDir &&
          cacheDir == other.cacheDir;
}

class PreferredJava {
  final int major;
  final String path;

  const PreferredJava({required this.major, required this.path});

  @override
  int get hashCode => major.hashCode ^ path.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PreferredJava &&
          runtimeType == other.runtimeType &&
          major == other.major &&
          path == other.path;
}

enum ThemePreference {
  system,
  light,
  dark;

  static Future<ThemePreference> default_() =>
      RustLib.instance.api.crateApiSettingsThemePreferenceDefault();
}

class UpdateInfo {
  final String version;
  final String url;
  final String notes;

  const UpdateInfo({
    required this.version,
    required this.url,
    required this.notes,
  });

  @override
  int get hashCode => version.hashCode ^ url.hashCode ^ notes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UpdateInfo &&
          runtimeType == other.runtimeType &&
          version == other.version &&
          url == other.url &&
          notes == other.notes;
}
