// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `hash`

class AppPaths {
  final String data;
  final String servers;
  final String runtimes;
  final String backups;
  final String cache;
  final String logs;

  const AppPaths({
    required this.data,
    required this.servers,
    required this.runtimes,
    required this.backups,
    required this.cache,
    required this.logs,
  });

  @override
  int get hashCode =>
      data.hashCode ^
      servers.hashCode ^
      runtimes.hashCode ^
      backups.hashCode ^
      cache.hashCode ^
      logs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AppPaths &&
          runtimeType == other.runtimeType &&
          data == other.data &&
          servers == other.servers &&
          runtimes == other.runtimes &&
          backups == other.backups &&
          cache == other.cache &&
          logs == other.logs;
}

class BackupInfo {
  final String fileName;
  final String path;
  final PlatformInt64 sizeBytes;
  final PlatformInt64 createdMs;

  const BackupInfo({
    required this.fileName,
    required this.path,
    required this.sizeBytes,
    required this.createdMs,
  });

  @override
  int get hashCode =>
      fileName.hashCode ^
      path.hashCode ^
      sizeBytes.hashCode ^
      createdMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BackupInfo &&
          runtimeType == other.runtimeType &&
          fileName == other.fileName &&
          path == other.path &&
          sizeBytes == other.sizeBytes &&
          createdMs == other.createdMs;
}

class BuildEntry {
  final String id;
  final bool stable;
  final String label;

  const BuildEntry({
    required this.id,
    required this.stable,
    required this.label,
  });

  @override
  int get hashCode => id.hashCode ^ stable.hashCode ^ label.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BuildEntry &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          stable == other.stable &&
          label == other.label;
}

class CreateServerRequest {
  final String name;

  /// Empty: a new folder inside the servers folder.
  final String root;
  final ProviderKind provider;
  final String mcVersion;

  /// Empty: latest build.
  final String build;

  /// Local jar used instead of a download (provider `Custom` or a known jar).
  final String jarPath;

  /// Empty: required Java chosen automatically (preferred runtime or download).
  final String javaHome;
  final String ramMin;
  final String ramMax;
  final List<String> jvmFlags;

  /// 0: first free port from the launcher settings.
  final int port;
  final String motd;
  final int maxPlayers;
  final String gamemode;
  final String difficulty;
  final bool onlineMode;
  final String levelSeed;
  final bool acceptEula;

  const CreateServerRequest({
    required this.name,
    required this.root,
    required this.provider,
    required this.mcVersion,
    required this.build,
    required this.jarPath,
    required this.javaHome,
    required this.ramMin,
    required this.ramMax,
    required this.jvmFlags,
    required this.port,
    required this.motd,
    required this.maxPlayers,
    required this.gamemode,
    required this.difficulty,
    required this.onlineMode,
    required this.levelSeed,
    required this.acceptEula,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      root.hashCode ^
      provider.hashCode ^
      mcVersion.hashCode ^
      build.hashCode ^
      jarPath.hashCode ^
      javaHome.hashCode ^
      ramMin.hashCode ^
      ramMax.hashCode ^
      jvmFlags.hashCode ^
      port.hashCode ^
      motd.hashCode ^
      maxPlayers.hashCode ^
      gamemode.hashCode ^
      difficulty.hashCode ^
      onlineMode.hashCode ^
      levelSeed.hashCode ^
      acceptEula.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CreateServerRequest &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          root == other.root &&
          provider == other.provider &&
          mcVersion == other.mcVersion &&
          build == other.build &&
          jarPath == other.jarPath &&
          javaHome == other.javaHome &&
          ramMin == other.ramMin &&
          ramMax == other.ramMax &&
          jvmFlags == other.jvmFlags &&
          port == other.port &&
          motd == other.motd &&
          maxPlayers == other.maxPlayers &&
          gamemode == other.gamemode &&
          difficulty == other.difficulty &&
          onlineMode == other.onlineMode &&
          levelSeed == other.levelSeed &&
          acceptEula == other.acceptEula;
}

class ImportPreview {
  final String name;
  final String root;
  final ProviderKind provider;
  final String mcVersion;
  final int javaMajor;
  final String javaHome;
  final String jarPath;
  final String ramMin;
  final String ramMax;
  final List<String> jvmFlags;
  final int pluginCount;
  final int worldCount;
  final bool hasEula;

  const ImportPreview({
    required this.name,
    required this.root,
    required this.provider,
    required this.mcVersion,
    required this.javaMajor,
    required this.javaHome,
    required this.jarPath,
    required this.ramMin,
    required this.ramMax,
    required this.jvmFlags,
    required this.pluginCount,
    required this.worldCount,
    required this.hasEula,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      root.hashCode ^
      provider.hashCode ^
      mcVersion.hashCode ^
      javaMajor.hashCode ^
      javaHome.hashCode ^
      jarPath.hashCode ^
      ramMin.hashCode ^
      ramMax.hashCode ^
      jvmFlags.hashCode ^
      pluginCount.hashCode ^
      worldCount.hashCode ^
      hasEula.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ImportPreview &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          root == other.root &&
          provider == other.provider &&
          mcVersion == other.mcVersion &&
          javaMajor == other.javaMajor &&
          javaHome == other.javaHome &&
          jarPath == other.jarPath &&
          ramMin == other.ramMin &&
          ramMax == other.ramMax &&
          jvmFlags == other.jvmFlags &&
          pluginCount == other.pluginCount &&
          worldCount == other.worldCount &&
          hasEula == other.hasEula;
}

class JavaReleaseInfo {
  final int major;
  final bool lts;

  const JavaReleaseInfo({required this.major, required this.lts});

  @override
  int get hashCode => major.hashCode ^ lts.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is JavaReleaseInfo &&
          runtimeType == other.runtimeType &&
          major == other.major &&
          lts == other.lts;
}

class JavaRuntimeInfo {
  final String name;
  final int major;
  final String path;

  /// Only managed runtimes can be deleted from the launcher.
  final bool managed;
  final bool system;

  const JavaRuntimeInfo({
    required this.name,
    required this.major,
    required this.path,
    required this.managed,
    required this.system,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      major.hashCode ^
      path.hashCode ^
      managed.hashCode ^
      system.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is JavaRuntimeInfo &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          major == other.major &&
          path == other.path &&
          managed == other.managed &&
          system == other.system;
}

class ModrinthProject {
  final String projectId;
  final String slug;
  final String title;
  final String description;
  final PlatformInt64 downloads;

  const ModrinthProject({
    required this.projectId,
    required this.slug,
    required this.title,
    required this.description,
    required this.downloads,
  });

  @override
  int get hashCode =>
      projectId.hashCode ^
      slug.hashCode ^
      title.hashCode ^
      description.hashCode ^
      downloads.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ModrinthProject &&
          runtimeType == other.runtimeType &&
          projectId == other.projectId &&
          slug == other.slug &&
          title == other.title &&
          description == other.description &&
          downloads == other.downloads;
}

class PluginInfo {
  final String fileName;
  final bool enabled;
  final PlatformInt64 sizeBytes;

  const PluginInfo({
    required this.fileName,
    required this.enabled,
    required this.sizeBytes,
  });

  @override
  int get hashCode => fileName.hashCode ^ enabled.hashCode ^ sizeBytes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PluginInfo &&
          runtimeType == other.runtimeType &&
          fileName == other.fileName &&
          enabled == other.enabled &&
          sizeBytes == other.sizeBytes;
}

class ProgressEvent {
  final String stage;
  final String message;
  final double? fraction;
  final bool done;
  final String? error;
  final String? serverId;

  const ProgressEvent({
    required this.stage,
    required this.message,
    this.fraction,
    required this.done,
    this.error,
    this.serverId,
  });

  @override
  int get hashCode =>
      stage.hashCode ^
      message.hashCode ^
      fraction.hashCode ^
      done.hashCode ^
      error.hashCode ^
      serverId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProgressEvent &&
          runtimeType == other.runtimeType &&
          stage == other.stage &&
          message == other.message &&
          fraction == other.fraction &&
          done == other.done &&
          error == other.error &&
          serverId == other.serverId;
}

class PropertyEntry {
  final String key;
  final String value;

  const PropertyEntry({required this.key, required this.value});

  @override
  int get hashCode => key.hashCode ^ value.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PropertyEntry &&
          runtimeType == other.runtimeType &&
          key == other.key &&
          value == other.value;
}

enum ProviderCategory { vanilla, plugins, modded, proxy, hybrid, other }

class ProviderInfo {
  final ProviderKind kind;
  final String id;
  final String name;
  final ProviderCategory category;
  final String description;
  final bool supportsPlugins;
  final bool supportsMods;
  final bool hasWorlds;
  final bool isProxy;

  /// Offers snapshot / pre-release versions.
  final bool hasSnapshots;

  /// Lets the user pick a specific build or loader version.
  final bool hasBuilds;
  final bool deprecated;

  /// Extra requirement shown in the wizard (e.g. Git for BuildTools).
  final String note;

  /// Config files worth editing for this server type, relative to the server folder.
  final List<String> configFiles;

  const ProviderInfo({
    required this.kind,
    required this.id,
    required this.name,
    required this.category,
    required this.description,
    required this.supportsPlugins,
    required this.supportsMods,
    required this.hasWorlds,
    required this.isProxy,
    required this.hasSnapshots,
    required this.hasBuilds,
    required this.deprecated,
    required this.note,
    required this.configFiles,
  });

  @override
  int get hashCode =>
      kind.hashCode ^
      id.hashCode ^
      name.hashCode ^
      category.hashCode ^
      description.hashCode ^
      supportsPlugins.hashCode ^
      supportsMods.hashCode ^
      hasWorlds.hashCode ^
      isProxy.hashCode ^
      hasSnapshots.hashCode ^
      hasBuilds.hashCode ^
      deprecated.hashCode ^
      note.hashCode ^
      configFiles.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProviderInfo &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          id == other.id &&
          name == other.name &&
          category == other.category &&
          description == other.description &&
          supportsPlugins == other.supportsPlugins &&
          supportsMods == other.supportsMods &&
          hasWorlds == other.hasWorlds &&
          isProxy == other.isProxy &&
          hasSnapshots == other.hasSnapshots &&
          hasBuilds == other.hasBuilds &&
          deprecated == other.deprecated &&
          note == other.note &&
          configFiles == other.configFiles;
}

enum ProviderKind {
  vanilla,
  paper,
  folia,
  purpur,
  pufferfish,
  leaf,
  spigot,
  fabric,
  quilt,
  forge,
  neoForge,
  velocity,
  bungeeCord,
  waterfall,
  mohist,
  arclight,
  spongeVanilla,
  spongeForge,

  /// A jar chosen by the user that VoxelPanel does not know how to update.
  custom;

  static Future<ProviderKind> default_() =>
      RustLib.instance.api.crateApiTypesProviderKindDefault();
}

class RamChoice {
  final int megabytes;
  final String label;
  final String value;

  const RamChoice({
    required this.megabytes,
    required this.label,
    required this.value,
  });

  @override
  int get hashCode => megabytes.hashCode ^ label.hashCode ^ value.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RamChoice &&
          runtimeType == other.runtimeType &&
          megabytes == other.megabytes &&
          label == other.label &&
          value == other.value;
}

class RamSuggestion {
  final String ramMin;
  final String ramMax;
  final String total;

  const RamSuggestion({
    required this.ramMin,
    required this.ramMax,
    required this.total,
  });

  @override
  int get hashCode => ramMin.hashCode ^ ramMax.hashCode ^ total.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RamSuggestion &&
          runtimeType == other.runtimeType &&
          ramMin == other.ramMin &&
          ramMax == other.ramMax &&
          total == other.total;
}

class ServerDetails {
  final String id;
  final String name;
  final String root;
  final ProviderKind provider;
  final String? mcVersion;
  final String? build;
  final int? javaMajor;
  final String javaHome;
  final String jarPath;
  final String ramMin;
  final String ramMax;
  final List<String> jvmFlags;
  final bool eulaAccepted;
  final PlatformInt64 createdUnix;
  final int port;
  final int maxPlayers;

  const ServerDetails({
    required this.id,
    required this.name,
    required this.root,
    required this.provider,
    this.mcVersion,
    this.build,
    this.javaMajor,
    required this.javaHome,
    required this.jarPath,
    required this.ramMin,
    required this.ramMax,
    required this.jvmFlags,
    required this.eulaAccepted,
    required this.createdUnix,
    required this.port,
    required this.maxPlayers,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      root.hashCode ^
      provider.hashCode ^
      mcVersion.hashCode ^
      build.hashCode ^
      javaMajor.hashCode ^
      javaHome.hashCode ^
      jarPath.hashCode ^
      ramMin.hashCode ^
      ramMax.hashCode ^
      jvmFlags.hashCode ^
      eulaAccepted.hashCode ^
      createdUnix.hashCode ^
      port.hashCode ^
      maxPlayers.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ServerDetails &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          root == other.root &&
          provider == other.provider &&
          mcVersion == other.mcVersion &&
          build == other.build &&
          javaMajor == other.javaMajor &&
          javaHome == other.javaHome &&
          jarPath == other.jarPath &&
          ramMin == other.ramMin &&
          ramMax == other.ramMax &&
          jvmFlags == other.jvmFlags &&
          eulaAccepted == other.eulaAccepted &&
          createdUnix == other.createdUnix &&
          port == other.port &&
          maxPlayers == other.maxPlayers;
}

/// Live state of one server, pushed by `watch_events` whenever something changes.
class ServerRuntime {
  final String serverId;
  final ServerStatus status;
  final int? pid;
  final PlatformInt64? startedUnix;
  final List<String> players;
  final double cpuPercent;
  final PlatformInt64 memoryBytes;
  final int? lastExitCode;
  final bool crashed;

  const ServerRuntime({
    required this.serverId,
    required this.status,
    this.pid,
    this.startedUnix,
    required this.players,
    required this.cpuPercent,
    required this.memoryBytes,
    this.lastExitCode,
    required this.crashed,
  });

  @override
  int get hashCode =>
      serverId.hashCode ^
      status.hashCode ^
      pid.hashCode ^
      startedUnix.hashCode ^
      players.hashCode ^
      cpuPercent.hashCode ^
      memoryBytes.hashCode ^
      lastExitCode.hashCode ^
      crashed.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ServerRuntime &&
          runtimeType == other.runtimeType &&
          serverId == other.serverId &&
          status == other.status &&
          pid == other.pid &&
          startedUnix == other.startedUnix &&
          players == other.players &&
          cpuPercent == other.cpuPercent &&
          memoryBytes == other.memoryBytes &&
          lastExitCode == other.lastExitCode &&
          crashed == other.crashed;
}

enum ServerStatus { stopped, starting, running, stopping }

class ServerSummary {
  final String id;
  final String name;
  final String root;
  final ProviderKind provider;
  final String? mcVersion;
  final String? build;
  final int? javaMajor;
  final String ramMin;
  final String ramMax;
  final int port;
  final int maxPlayers;

  const ServerSummary({
    required this.id,
    required this.name,
    required this.root,
    required this.provider,
    this.mcVersion,
    this.build,
    this.javaMajor,
    required this.ramMin,
    required this.ramMax,
    required this.port,
    required this.maxPlayers,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      root.hashCode ^
      provider.hashCode ^
      mcVersion.hashCode ^
      build.hashCode ^
      javaMajor.hashCode ^
      ramMin.hashCode ^
      ramMax.hashCode ^
      port.hashCode ^
      maxPlayers.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ServerSummary &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          root == other.root &&
          provider == other.provider &&
          mcVersion == other.mcVersion &&
          build == other.build &&
          javaMajor == other.javaMajor &&
          ramMin == other.ramMin &&
          ramMax == other.ramMax &&
          port == other.port &&
          maxPlayers == other.maxPlayers;
}

class VersionEntry {
  final String id;
  final bool stable;

  const VersionEntry({required this.id, required this.stable});

  @override
  int get hashCode => id.hashCode ^ stable.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VersionEntry &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          stable == other.stable;
}

class WorldInfo {
  final String name;
  final String path;
  final PlatformInt64 sizeBytes;
  final PlatformInt64 modifiedMs;
  final bool active;

  const WorldInfo({
    required this.name,
    required this.path,
    required this.sizeBytes,
    required this.modifiedMs,
    required this.active,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      path.hashCode ^
      sizeBytes.hashCode ^
      modifiedMs.hashCode ^
      active.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WorldInfo &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          path == other.path &&
          sizeBytes == other.sizeBytes &&
          modifiedMs == other.modifiedMs &&
          active == other.active;
}
